name: AI Code Review
on: [pull_request]
jobs:
  code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      # THIS points to the repo we just pushed!
      - uses: ishpreet7226/code-reviewer@main 
        with:
          api-to-use: 'anthropic'
          anthropic-key: ${{ secrets.ANTHROPIC_API_KEY }}
          model: 'claude-3-haiku-20240307'
          persona: 'kent_beck'
          style: 'concise'
